### ISSUE TITLE
Support for multi-region cases

### ISSUE THREAD

**Issue by OpenFoam-User** [fluiddyn/fluidfoam#29]
Hello,
First off, thank you for this package. I have seen several using it successfully to post-process their OpenFOAM cases. But in all those cases, the mesh must be without multiple regions.

In some cases such as when using the Arbitrary mesh interface (using a sliding interface between two regions: a rotating region and a fixed domain), it's not possible to use `fluidfoam` to read the case.

I would like to ask if there are any planes to add this feature?

Best regards

**Comment by CyrilleBonamy** [comment]
Hello,

Thanks a lot for opening an issue!

Currently, Dynamic Mesh is not supported by fluidfoam (because the mesh points move at each timestep).
However i think it is not very difficult to support.

If you want to test very quickly i can suggest a workaround : 
- First, generate Cx, Cy and Cz in each time directory : `postProcess -func writeCellCentres`
- Then, you can read (for each time) x, y, z and the corresponding fields : 
```
cx = readscalar(sol, timename, 'Cx')
cy = readscalar(sol, timename, 'Cy')
cz = readscalar(sol, timename, 'Cz')
nut = readscalar(sol, timename, 'nut')
```

At the end, you have 4 one-dimensional vectors of size Ncell. Then, you can for example interpolate on a grid as in the unstructured fluidfoam example : https://fluidfoam.readthedocs.io/en/latest/auto_examples/unstructured/plot_contour_unstructured.html#sphx-glr-auto-examples-unstructured-plot-contour-unstructured-py

Does it meet your needs?

**Comment by SignificantCell2** [comment]
Hello
Thank you for the suggestion. I  will take a look at how to do interpolation in Python (since I am not familiar  with it)

But of course, a native solution integrated to this package will be a huge plus for the OpenFOAM community.

Thank you

**Comment by CyrilleBonamy** [comment]
I just added support for dynamic Mesh.
But you have to use the time_name option of the readmesh function. I will add an example to explain this very quickly.

Regarding the interpolation, you can read the [unstructured examples](https://fluidfoam.readthedocs.io/en/latest/auto_examples/index.html#examples-for-unstructured-mesh). I just added an example to plot a contour without interpolation : https://fluidfoam.readthedocs.io/en/latest/auto_examples/unstructured/plot_tricontourf_unstructured.html#sphx-glr-auto-examples-unstructured-plot-tricontourf-unstructured-py

**Comment by SignificantCell2** [comment]
Wow! Such a great update! 
I confirm that I can successfully read a sliding mesh simulation with the flag `structured=False`.

I deal exclusively with multi-block structured meshes. I wonder if it's possible for `fluidfoam` to recognize the blocks and read the whole mesh as structured (that will tremendously avoid the user to use interpolation in such cases).

One critical step I always needed is to plot the structured grid in matplotlib and taking advantage of the flexibility offered by Matplotlib to display specific parts of the grid and export them in a vector format (such as EPS, PDF, SVG, etc.). Currently I don't know how to do that in Matplotlib. I am still using Tecplot for that purpose, and I am sure, I will no longer need Tecplot if fluidfoam makes that possible!

I do really believe that the OpenFOAM community should be proud of this package.

**Comment by OpenFoam-User** [comment]
The main issue (reading dynamic cases) is solved. I believe the rest is similar to #32

**Comment by fab6** [comment]
Hi,
I am not exactly sure if the multi-region should be working now!? E.g. how could we read scalar values from the different regions for the `multiRegionHeater` case, which has 5 regions (fixed mesh)? And if this is not working, would that be a lot of work to get this into the code? 
Thank you in advance!
Fab

**Comment by CyrilleBonamy** [comment]
I was not aware of this type of multi-region case.
Currently, it is not possible to associate the field with a mesh for a specific region. However, it is possible to read a region field and have a numpy array with the values, but without knowing the associated mesh it is not very useful...

Nevertheless, I think that there is not much work to integrate this functionality of reading a region in the fluidfoam code because it is enough to read and associate the right files...
Do you need this for your work ? And what is your job ?
And perhaps you could open a specific issue on this subject ?

**Comment by fab6** [comment]
Hi,
thanks for your quick help!
Yes, it would be very helpful for our research work, I am working at the university of wuppertal.
I would open another issue... Thanks!
