### ISSUE TITLE
Normal derivative

### ISSUE THREAD

**Issue by KarfiolosHus** [fluiddyn/fluidfoam#58]
Hello!

First of all, thank you for this project, helped me a lot with my problem with multiple cases.

My problem consists of a heated plate in a buoyancy driven flow, and I need to calculate to heat flux and the drag coefficient (because my solver doesn't support wallHeatFlux utility and I couldn't read wallShearStress). 

Is there a way to retrieve the normal vector from the boundary surface and values in the cell above it?

Thank you for your help in advance!

**Comment by CyrilleBonamy** [comment]
Hello !
Thank you for your interest in fluidfoam!

Fluidfoam does not support this feature ("retrieve the normal vector from the boundary/patch").
I think the easiest way to solve your problem is to adapt the wallHeatFlux and wallShearStress utilities to your solver. It's certainly not too difficult.

Have a nice day
Cyrille
